version: '3.8'

services:
  ecmn:
    image: jinvic/ecmn:latest
    container_name: ecmn
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
